var config = [

    /****************************************** 		level 1 ----------- animals 		******************************************/
    {level:"1", theme: "animals", question: "Which of these was not a red flag in relation to the Olympus scandal?", answers: ["High R&D expenditure", "Abrupt dismissal of its CEO", "Rapid and unexplained acquisitions", "Inadequate financial disclosures"], correct: 1},
    {level:"1", theme: "animals", question: "Which of these is not considered a fraudulent practice to inflate sales?", answers: ["Recording fictitious sales", "Channel stuffing", "Inflating revenue through acquisition", "Offering clients generous incentives, discounts, or promotions"], correct: 4},
    {level:"1", theme: "animals", question: "Which of these were red flags uncovered from Wirecard fraud case?", answers: ["Missing Cash Balances", "Delayed and incomplete audit reports", "Artificial inflation of profit", "All of the mentioned"], correct: 4},
    {level:"1", theme: "animals", question: "How should you deal with a public listed company that is suppose to file but delays its financials?", answers: ["Check if financials are filed on time (~90 days from FYE date)", "Tighten underwriting policies to account for FS quality", "Check for consolidated financial statements", "All of the mentioned"], correct: 4},
    {level:"1", theme: "animals", question: "A company reports healthy cash flow from operations but chooses to classify trade financing and bills payables under working capital changes.  What category of red flags does this fall under?", answers: ["Window dressing", "Hidden Woes", "Outright fraud", "None of the mentioned"], correct: 1},
    {level:"1", theme: "animals", question: "Which of the following companies have been involved in accounting scandals due to highly complex accounting methods?", answers: ["WorldCom", "Enron", "Satyam Computer Services", "All of the mentioned"], correct: 4},
    {level:"1", theme: "animals", question: "Which fraudulent scheme did employees at Wells Fargo use where they created fake accounts for customers to meet sales target and earn bonuses?", answers: ["Identity theft", "Money laundering", "Ponzi scheme", "Account fraud"], correct: 4},
    {level:"1", theme: "animals", question: "Which of the following is a red flag?", answers: ["Timely filing of taxes", "Consistent overvaluation of assets", "Regularly hiring external auditors", "Keeping accourate financial records"], correct: 2}   
    ];
